#LOADER END

###*
# Created by rome0s on 10/28/16.
###

#LOADER START

loader_init = ($element, type) ->
  switch type
    when 'before'
      $element.before '<div class="text-center loader">' + '<img src="/uploads/loaders/loader.svg" />' + '</div>'
    when 'after'
      $element.after '<div class="text-center loader">' + '<img src="/uploads/loaders/loader.svg" />' + '</div>'
    else
      $element.html '<div class="text-center loader">' + '<img src="/uploads/loaders/loader.svg" />' + '</div>'
      break
  return

loader_remove = ->
  $('.loader').remove()
  return

# ---
# generated by js2coffee 2.2.0