#LISTENERS
#MESSAGES START

error_message = (status, message) ->
  html = '<div class="message_popup">' + '<a class="pull-right">' + '<i class="fa fa-times-circle-o" aria-hidden="true"></i></a>' + '<p class="text-' + status + '">' + message + '</p></div>'
  $('div.messages').append html
  erase_messages()
  return

erase_messages = ->
  setTimeout (->
    $('.message_popup').fadeOut 'slow'
    return
  ), 5000
  return

$(document).on 'click', '.message_popup a', ->
  $(this).parent('div.message_popup').remove()
  return
#MESSAGES END

# ---
# generated by js2coffee 2.2.0